apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstack-autoscaler.fullname" . }}-config
  labels:
    {{- include "openstack-autoscaler.labels" . | nindent 4 }}
  {{- include "openstack-autoscaler.annotations" . | nindent 4 }}
data:
  config.yaml: |
    cloud:
      auth_url: ""
      username: ""
      password: ""
      project_name: ""
      project_id: ""
      user_domain_name: "Default"
      project_domain_name: "Default"
      region: ""
      interface: "public"
      identity_api_version: "3"
      compute_api_version: "2.1"
      network_api_version: "2.0"