{{- if not .Values.openstack.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstack-autoscaler.fullname" . }}-openstack
  labels:
    {{- include "openstack-autoscaler.labels" . | nindent 4 }}
  {{- include "openstack-autoscaler.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.openstack.auth }}
  OS_AUTH_URL: {{ .authUrl | b64enc | quote }}
  OS_USERNAME: {{ .username | b64enc | quote }}
  OS_PASSWORD: {{ .password | b64enc | quote }}
  OS_PROJECT_NAME: {{ .projectName | b64enc | quote }}
  {{- if .projectId }}
  OS_PROJECT_ID: {{ .projectId | b64enc | quote }}
  {{- end }}
  OS_USER_DOMAIN_NAME: {{ .userDomainName | b64enc | quote }}
  OS_PROJECT_DOMAIN_NAME: {{ .projectDomainName | b64enc | quote }}
  OS_REGION_NAME: {{ .region | b64enc | quote }}
  OS_INTERFACE: {{ .interface | b64enc | quote }}
  {{- end }}
{{- end }}