{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openstack-autoscaler.serviceAccountName" . }}
  labels:
    {{- include "openstack-autoscaler.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "openstack-autoscaler.annotations" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}