apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstack-autoscaler.fullname" . }}
  labels:
    {{- include "openstack-autoscaler.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- include "openstack-autoscaler.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{- include "openstack-autoscaler.selectorLabels" . | nindent 4 }}